[package]
name = "MiniLog"
version = "0.1.0"
edition = "2021"
authors = ["WuYuMaoMao"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_xlsxwriter = "0.79.0"
hotkey-rs = "0.1.2"
